import { useState } from 'react';
import type { ReactElement } from 'react';

import type { Report } from '../types';
import { isoDate, num } from './format';
import { H, HeadingBase } from './heading';
import { Stat, StatRow } from './parts';
import { dashboardSections } from './sections';

export type ReportTheme = 'light' | 'dark';

interface ReportDashboardProps {
  report: Report;
  /**
   * True inside the local application, which already names the repository and
   * owns the theme, the page landmarks and the footer's claim about files.
   */
  embedded?: boolean;
  /** The embedding application's theme. The static page follows the system. */
  theme?: ReportTheme;
}

/**
 * The repository dashboard. The static CLI page and the local application
 * render this same component, so both show the same sections for a report.
 */
export function ReportDashboard({ report, embedded = false, theme }: ReportDashboardProps): ReactElement {
  const sections = dashboardSections.map((Section, index) => <Section key={index} report={report} />);

  if (embedded) {
    return (
      <HeadingBase.Provider value={2}>
        <div className="cg-report cg-report-embedded" data-theme={theme}>
          <Summary report={report} embedded />
          <Warnings report={report} />
          <div className="report-sections">{sections}</div>
          <footer className="page-footer">
            <p>Generated by Commitography — MIT licensed.</p>
            <p>No data left this machine. The local server read the repository and keeps this report in memory only.</p>
          </footer>
        </div>
      </HeadingBase.Provider>
    );
  }

  return (
    <HeadingBase.Provider value={1}>
      <div className="cg-report page">
        <Summary report={report} />
        <Warnings report={report} />
        <main id="content">{sections}</main>
        <footer className="page-footer">
          <p>Generated by Commitography — MIT licensed.</p>
          <p>No data left this machine. The tool reads the repository and writes this file; it makes no network requests.</p>
        </footer>
      </div>
    </HeadingBase.Provider>
  );
}

function Summary({ report, embedded = false }: { report: Report; embedded?: boolean }): ReactElement {
  const repo = report.repository;
  const range =
    repo.firstCommit && repo.lastCommit ? `${isoDate(repo.firstCommit)} – ${isoDate(repo.lastCommit)}` : 'no dated commits';

  const body = (
    <>
      <p className="repo-range">{range}</p>
      <StatRow>
        <Stat value={num(repo.commitsAnalyzed)} label="commits analyzed" note={`${num(repo.commitsTotal)} in history`} />
        <Stat value={num(repo.contributors)} label="contributors" />
        <Stat value={num(repo.ageDays)} label="days of history" />
        <Stat value={num(repo.trackedFiles)} label="files tracked" note={`${num(repo.trackedLines)} lines`} />
      </StatRow>
      <p className="meta-line">
        {`Analyzed ${isoDate(report.generatedAt)} with commitography ${report.toolVersion}`}
        {repo.headCommit ? ` at ${repo.headCommit.slice(0, 10)}` : ''}
      </p>
    </>
  );

  // Inside the application the job view is the title; a second banner
  // landmark there would only repeat it.
  if (embedded) return <div className="page-header">{body}</div>;

  return (
    <header className="page-header">
      <div className="page-header-top">
        <H depth={0} className="repo-name">
          {repo.name || 'repository'}
        </H>
        <ThemeToggle />
      </div>
      {body}
    </header>
  );
}

/** Switches the static page theme. Held in memory only: the page uses no storage API. */
function ThemeToggle(): ReactElement {
  const [label, setLabel] = useState<string>();
  const toggle = () => {
    const root = document.documentElement;
    const current = root.dataset.theme ?? (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light');
    const next = current === 'dark' ? 'light' : 'dark';
    root.dataset.theme = next;
    setLabel(`Switch to ${next === 'dark' ? 'light' : 'dark'} theme`);
  };
  return (
    <button type="button" className="theme-toggle" aria-label={label} onClick={toggle}>
      Switch theme
    </button>
  );
}

function Warnings({ report }: { report: Report }): ReactElement | null {
  if (report.warnings.length === 0) return null;
  return (
    <div className="banner" role="status">
      <strong>{report.warnings.length === 1 ? 'Warning' : 'Warnings'}</strong>
      <ul>
        {report.warnings.map((warning, index) => (
          <li key={index}>{warning}</li>
        ))}
      </ul>
    </div>
  );
}
